config/routes.rb
TestDos::Application.routes.draw do
  get "reports/show"

  resources :comments


  resources :posts


  get "posts/get_popular_posts"

  post "posts/search_posts"
  get "auth/login"

  get "auth/logout"

  get "auth/index"
  get "auth/register"
  post "auth/register_post"
  post "auth/login_post"

  resources :users












  root :to => 'auth#index'


end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :user_id, :post_id, :author
  validates :author,  :presence => true
  validates :post_id,  :presence => true

  belongs_to :post
end

app/controllers/comments_controller.rb

class CommentsController < ApplicationController
  #Admin can see list of comments, delete comments
  before_filter :has_admin_access , :only => [:index,:destroy ]







  # GET /comments/show_for_post/postid
  def show_for_post
    @post = Post.find(params[:id])
    postid = -1
    if @post
      postid = @post.id
    end

         #GET comments for this post
      @comments = Comment.find_all_by_post_id(postid)
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @comments }
      end





  end




  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end


  #get post info and create comment for that
  # POST /comments
  # POST /comments.json
  def create

    @post = Post.find(params[:post_id])
    @comment = Comment.new


    @comment.content =  params[:content]
    @comment.post_id = params[:post_id]
    @comment.author = params[:author]
    #add userid to comment if logged in
    if session[:user_id]
      @comment.user_id = session[:user_id]
      anyuser = User.find(session[:user_id])
      if anyuser
        @comment.author = anyuser.username
      else
        @comment.author = "Nobody!!!"
      end
    end

    #Prevent comments from post's owner
    if session[:user_id] == @post.user_id
        flash[:notice] = "You cannot create comment for your own post."

    else
      if @comment.save
        flash[:notice] = "SAVED...."
      else
        flash[:notice] = "NOT SAVED !!!"
      end
    end


    redirect_to @post


   end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])
    if  session[:user_admin]
      respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
      end
    else
      flash[:notice] = "Admin can edit comments...."
      redirect_to @comment
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>

    <div class="field">
      <%= f.label :post_id %><br />
      <%= f.number_field :post_id %>
    </div>


    <% if session[:user_id].nil? %>

    <div class="field">
      <%= f.label :author %><br />
      <%= f.number_field :author %>
    </div>
    <% end %>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/_show_for_post.html.erb
<div class="post_comment">
<p>
  <b>Content:</b>
  <%= @post.content %>
</p>



  <p>
    <b>Vote:</b>
    <%= @post.vote %>
  </p>

  <%  if @post.user %>
<p>
  <b>User:</b>
  <%= @post.user.username %>
</p>

<% end %>
</div>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>

    <th>Content</th>
    <th>Author</th>
    <th>Vote</th>
    <th>Post</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>

    <td><%= comment.content %></td>

    <td><%= comment.author %></td>
    <td><%= comment.vote %></td>
    <td>
      <%= comment.post.title %>
    </td>

    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p>
  <b>Content:</b>
  <%= @comment.content %>
</p>



<p>
  <b>User:</b>
  <%= @comment.user_id %>
</p>

<p>
  <b>Vote:</b>
  <%= @comment.vote %>
</p>

<p>
  <b>Post:</b>
  <%= @comment.post_id %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>