config/routes.rb
TestDos::Application.routes.draw do
  get "reports/show"

  resources :comments


  resources :posts


  get "posts/get_popular_posts"

  post "posts/search_posts"
  get "auth/login"

  get "auth/logout"

  get "auth/index"
  get "auth/register"
  post "auth/register_post"
  post "auth/login_post"

  resources :users












  root :to => 'auth#index'


end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :admin_flag, :description, :email, :first_name, :last_name, :password, :username ,:password_confirmation

  validates :username,  :presence => true  , :uniqueness => true
  validates :email,  :presence => true  ,:uniqueness => true  ,:format => { :with => /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/,
                                                                            :message => "is not valid!" }
  validates :password,  :presence => true ,:confirmation => true,:on => :create #add password_confirmation #validate for create action
  validates :first_name,  :presence => true
  validates :last_name,  :presence => true

  has_many :posts


  before_create :hashpassword
  OURSECRECTTOKEN = "dfgdfghoi3h45hgdlfghl4e3434g34g34"

  def has_same_password(checkpass)
    return self.password ==  Digest::MD5.hexdigest("-#{checkpass}#{OURSECRECTTOKEN}")
  end

  #find user by name or email and then check password .
  #Class method
  def self.authenticate(username_or_email,pass)
    @user = User.find_by_username( username_or_email)
    if @user.nil?
      @user = User.find_by_email(username_or_email)
    end

    #if we got user, we need to check password
    if @user.nil?
      return false
    end
    #check if password is right
    if @user.has_same_password(pass)
      return @user
    end
    return false
  end

  protected
  def hashpassword
    self.password = Digest::MD5.hexdigest("-#{self.password}#{OURSECRECTTOKEN}")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #filter action request for ADMIN login to specific methods
  #Admin can create users from this screen
  before_filter :has_admin_access , :only => [:index ]
  #filter action request for login
  before_filter :authorize , :except => [:login,:login_post,:new,:create]


  # Only admin can list all users
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    secure_user_access
  end

  def secure_user_access
    if !session[:user_admin]
      #not admin so check if userid is same as this object user is editing
      #if not redirect to unauth
      if @user.id != session[:user_id]
        flash[:notice] = "Not admin and not same user"
        redirect_to :action => "unauthorized"
      end
    end
  end

  # POST /users
  # POST /users.json
  def create


    @user = User.new(params[:user])



    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
    secure_user_access
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    secure_user_access
    @user.destroy
    @user.posts.each{|post| post.destroy}

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <% if @user.username != nil %>
      <p>
        <b>Username:</b>
        <%= @user.username %>
     </p>
   <% else %>
      <div class="field">
        <%= f.label :username %><br />
        <%= f.text_field :username %>
      </div>
   <% end %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>

  <% if @user.id.nil? %>
  <div class="field">
    <%= f.label :password %><br />
    <%= password_field(:user, :password, :size => 20) %>
  </div>
    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= password_field(:user, :password_confirmation, :size => 20) %>
  </div>

  <% end %>

    <% if !@user.id.nil? %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
        <% end %>
  <% if session[:user_admin] && session[:user_id] != @user.id && @user.username != "admin"%>

   <div class="field">
    <%= f.label :admin_flag %><br />
    <%= f.check_box :admin_flag %>
  </div>

        <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<% if session[:user_admin] == true %>
    <%= link_to 'Back', users_url %>
<% end %>
<% if session[:user_admin] != true %>
    <%= link_to 'Back', posts_url %>
<% end %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Description</th>
    <th>Admin flag</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.email %></td>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>

    <td><%= user.description %></td>
    <td><%= user.admin_flag %></td>

    <% if user.username != "admin"  %>

       <td><%= link_to 'Show', user %></td>
       <td><%= link_to 'Edit', edit_user_path(user) %></td>
       <% if user.username != session[:user_name]  %>
          <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
       <% end %>
    <% elsif user.username == "admin" && session[:user_name] =="admin" %>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td></td>
    <% end %>




  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<% if session[:user_admin] %>
    <%= link_to 'Back', users_path %>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>


<p>
  <b>Description:</b>
  <%= @user.description %>
</p>

<p>
  <b>Admin flag:</b>
  <%= @user.admin_flag %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |

<% if session[:user_admin] == true %>
    <%= link_to 'Back', users_url %>
<% end %>
<% if session[:user_admin] != true %>
    <%= link_to 'Back', posts_url %>
<% end %>