config/routes.rb
TestDos::Application.routes.draw do
  get "reports/show"

  resources :comments


  resources :posts


  get "posts/get_popular_posts"

  post "posts/search_posts"
  get "auth/login"

  get "auth/logout"

  get "auth/index"
  get "auth/register"
  post "auth/register_post"
  post "auth/login_post"

  resources :users












  root :to => 'auth#index'


end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def show
    #top 10 posts
    @posts = Post.find_by_sql("select  *,(select count(id) from comments where post_id = p.id) as vote from posts p

       order by vote desc, created_at desc")

    @userstats = []
    @userstats = User.find_by_sql("select id,
                                  username,
                              (select count(id) from comments where user_id = u.id) as totalcomments,
                              (select count(id) from posts where user_id = u.id) as totalposts,
                              (select updated_at  from posts where user_id = u.id order by updated_at  desc limit 1) as post_date,
                              (select  updated_at  from comments where user_id = u.id order by updated_at  desc limit 1) as comment_date
                              from users u

       order by totalposts desc, totalcomments desc limit 10 ")


  end
end

app/helpers/reports_helper.rb
module ReportsHelper


  class UserStat
    def initialize
      @username = ""
      @totalposts = 0
      @totalcomments = 0
      @last_activity_date = nil
      @userid = 0
      @userobj = nil
    end
  end
end

app/views/reports/show.html.erb
<h1>Reports for Admin</h1>


<h2>Top 10 posts</h2>
<table>
  <tr>

    <th>Title</th>

    <th>User</th>
    <th>Vote</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <td>

    <% @posts.each do |post| %>
        <tr>
          <td><%= post.title %></td>

          <td>
            <% if post.user && post.user.username %>


                <%= post.user.username %>
            <% end %>
          </td>
          <td><%= post.vote %></td>
          <td><%= link_to 'Show', post %></td>

          <td>

                <%= link_to 'Edit', edit_post_path(post) %>

          </td>

          <td>

                <%= link_to 'Destroy', post, confirm: 'Are you sure?', method: :delete %>

          </td>

        </tr>
    <% end %>
    </table>




<h2>Top 10 Users ordered by total posts and then total comments</h2>
<table>
  <tr>

    <th>User</th>
    <th>Total posts</th>
    <th>Total comments</th>
    <th>Last Post Activity Date</th>
    <th>Last Comment Activity Date</th>
    <th></th>

  </tr>

  <td>

    <% @userstats.each do |user| %>
        <tr>
          <td><%= user.username %></td>
          <td><%= user.totalposts %></td>
          <td><%= user.totalcomments %></td>
          <td><%= user.post_date %></td>
          <td><%= user.comment_date %></td>
          <td><%= link_to "show", user_path(user.id)   %></td>




        </tr>
    <% end %>
    </table>